[package]
name = "hex-aes-hmac"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8"
anyhow = "1.0"
cbc = { version = "0.1", features = ["alloc", "block-padding"] }
hex = "0.4"
hmac = "0.12"
rand = "0.8"
rand_core = "0.6"
sha2 = "0.10"
